endpoint: "wss://kusama-rpc.polkadot.io/"
check:
  authoredBlocks:
    start: 452074
    end: 452655
    author: EafgFRX24PTgJAjGoaDuQLXQiLX4daSFQQttzGVticSD18o
  events:
    start: 452074
    end: 452655
    section: imOnline
    method: HeartbeatReceived
    match:
      data: ["EafgFRX24PTgJAjGoaDuQLXQiLX4daSFQQttzGVticSD18o"]
